### ISSUE TITLE
CSS Cleanup

### ISSUE THREAD

**Issue by erickhiu** [erickhiu/erickhiu#4]
1. Dimensions: Make sure compatible with different window size/ devices. 
2. Try to reuse existing classes as much as possible across pages. Hopefully this will fix issue #1. 
3. Keep font, font size, font color, weights, spacing consistent across pages. 
4. Text with clickable links: Underline when hover over. Also need to fix some JS logic for clicking on project card- opening the same page when the link is not available for some reasons.
5. Better/ less awkward background handling: Current two-column structure for Projects and Publications is awkward. 
6. Need better UI for Projects/Publications filter system. See issue #2 
7. Publications: Abstract truncation- needs a solution that makes sense for window size of varying sizes/ different devices. Ideally have ellipses at the end before truncation. See issue #3 .

**Comment by farhan-t-dev** [comment]
Hi eric,
Its me Farhan T. The freelancer you chose to work with in fiverr. I saw your problems and don't worry I'll try my best to solve all your problem you have with the website. So please add me as a collaborator of this project and I'll keep you updated in fiverr.
